from langchain_core.documents import Document
from langchain_community.graphs.graph_document import GraphDocument, Node, Relationship

nodes = {
"node1":Node(id='Stress', type='Concept'),
"node2":Node(id='Heart Disease', type='Disease'),
"node3":Node(id='Burnout', type='Condition'),
"node4":Node(id='Mental Health', type='Aspect'),
"node5":Node(id='Physical Activity', type='Behavior'),
"node6":Node(id='Job Satisfaction', type='Emotional state'),
"node7":Node(id='Obesity', type='Condition'),
"node8":Node(id='Aging', type='Condition'),
"node9":Node(id='Diet', type='Condition'),
"node10":Node(id='Inflammation', type='Condition'),
"node11":Node(id='Genetics', type='Biological factor'),
"node12":Node(id='Depression', type='Condition'),
"node13":Node(id='Exercise', type='Lifestyle factor'),
"node14":Node(id='Memory', type='Condition'),
"node15":Node(id='Exercise', type='Factor'),
"node16":Node(id='Depression', type='Mental condition'),
"node17":Node(id='Employee Turnover', type='Outcome'),
"node18":Node(id='Social Support', type='Social factor'),
"node19":Node(id='Cognitive Function', type='Condition'),
"node20":Node(id='Job Satisfaction', type='Condition'),
"node21":Node(id='Social Support', type='Behavior'),
"node22":Node(id='Work Environment', type='Factor'),
"node23":Node(id='Job Satisfaction', type='Workplace factor'),
"node24":Node(id='Job Satisfaction', type='Psychological factor'),
"node25":Node(id='Immune System', type='Biological system'),
"node26":Node(id='Social Support', type='Factor'),
"node27":Node(id='Immune System', type='System'),
"node28":Node(id='Diet', type='Behavior'),
"node29":Node(id='Physical Health', type='Health aspect'),
"node30":Node(id='Productivity', type='Outcome'),
"node31":Node(id='Anxiety', type='Emotional state'),
"node32":Node(id='Sleep Quality', type='Health aspect'),
"node33":Node(id='Cortisol', type='Hormone'),
"node34":Node(id='Diet', type='Lifestyle factor'),
"node35":Node(id='Diet', type='Factor'),
"node36":Node(id='Social Relationships', type='Condition'),
"node37":Node(id='Mental Health', type='Health aspect'),
"node38":Node(id='Social Support', type='Aspect'),
"node39":Node(id='Work Environment', type='Environment'),
"node40":Node(id='Physical Health', type='Condition'),
"node41":Node(id='Exercise', type='Activity'),
"node42":Node(id='Physical Activity', type='Activity'),
"node43":Node(id='Cognitive Function', type='Function'),
"node44":Node(id='Sleep Quality', type='Condition'),
"node45":Node(id='Anxiety', type='Condition'),
"node46":Node(id='Mental Health', type='Condition'),
"node47":Node(id='Heart Rate', type='Physiological measure'),
"node48":Node(id='Anxiety', type='Mental condition'),
"node49":Node(id='Smoking', type='Activity'),
"node50":Node(id='Diet', type='Aspect'),
"node51":Node(id='Genetics', type='Factor'),
"node52":Node(id='Blood Pressure', type='Physiological measure'),
"node53":Node(id='Stress', type='Condition'),
"node54":Node(id='Social Support', type='Activity'),
"node55":Node(id='Heart Disease', type='Condition'),
"node56":Node(id='Smoking', type='Lifestyle'),
"node57":Node(id='Genetics', type='Aspect'),
"node58":Node(id='Diet', type='Activity'),
"node59":Node(id='Blood Pressure', type='Condition'),
"node60":Node(id='Alcohol Consumption', type='Activity'),
"node61":Node(id='Inflammation', type='Biological process'),
"node62":Node(id='Productivity', type='Condition'),
"node63":Node(id='Alcohol Consumption', type='Lifestyle'),
"node64":Node(id='Work Environment', type='Condition'),
"node65":Node(id='Diet', type='Lifestyle'),
"node66":Node(id='Diabetes', type='Disease'),
"node67":Node(id='Learning', type='Condition'),
"node68":Node(id='Work Performance', type='Condition'),
"node69":Node(id='Depression', type='Emotional state'),
"node70":Node(id='Sleep Quality', type='Aspect'),
"node71":Node(id='Social Support', type='Condition'),
}

links = {
"rel1":Relationship(source=Node(id='Immune System', type='System'), target=Node(id='Inflammation', type='Condition'), type='REDUCES'),
"rel2":Relationship(source=Node(id='Inflammation', type='Condition'), target=Node(id='Heart Disease', type='Disease'), type='CAUSES'),
"rel3":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Sleep Quality', type='Health aspect'), type='DECREASES'),
"rel4":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Diet', type='Lifestyle factor'), type='WORSENS'),
"rel5":Relationship(source=Node(id='Job Satisfaction', type='Psychological factor'), target=Node(id='Stress', type='Condition'), type='REDUCES'),
"rel6":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Physical Health', type='Condition'), type='IMPAIRS'),
"rel7":Relationship(source=Node(id='Burnout', type='Condition'), target=Node(id='Mental Health', type='Condition'), type='DETERIORATES'),
"rel8":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Work Environment', type='Environment'), type='INFLUENCED_BY'),
"rel9":Relationship(source=Node(id='Cortisol', type='Hormone'), target=Node(id='Depression', type='Condition'), type='INCREASES'),
"rel10":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Mental Health', type='Health aspect'), type='AFFECTS'),
"rel11":Relationship(source=Node(id='Diet', type='Factor'), target=Node(id='Physical Health', type='Condition'), type='AFFECTS'),
"rel12":Relationship(source=Node(id='Alcohol Consumption', type='Activity'), target=Node(id='Mental Health', type='Condition'), type='AFFECTS'),
"rel13":Relationship(source=Node(id='Mental Health', type='Health aspect'), target=Node(id='Anxiety', type='Condition'), type='INCLUDES'),
"rel14":Relationship(source=Node(id='Social Support', type='Activity'), target=Node(id='Sleep Quality', type='Condition'), type='IMPROVES'),
"rel15":Relationship(source=Node(id='Cortisol', type='Hormone'), target=Node(id='Cognitive Function', type='Condition'), type='IMPAIRS'),
"rel16":Relationship(source=Node(id='Anxiety', type='Condition'), target=Node(id='Stress', type='Condition'), type='INCREASES'),
"rel17":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Aging', type='Condition'), type='ACCELERATES'),
"rel18":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Diet', type='Behavior'), type='WORSENS'),
"rel19":Relationship(source=Node(id='Exercise', type='Activity'), target=Node(id='Physical Health', type='Condition'), type='IMPROVES'),
"rel20":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Job Satisfaction', type='Condition'), type='REDUCES'),
"rel21":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Mental Health', type='Condition'), type='IMPACTS'),
"rel22":Relationship(source=Node(id='Diabetes', type='Disease'), target=Node(id='Heart Disease', type='Disease'), type='INCREASES_RISK'),
"rel23":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Work Environment', type='Environment'), type='WORSENS'),
"rel24":Relationship(source=Node(id='Job Satisfaction', type='Emotional state'), target=Node(id='Burnout', type='Condition'), type='REDUCES'),
"rel25":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Physical Activity', type='Activity'), type='DECREASES'),
"rel26":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Social Support', type='Activity'), type='DECREASES'),
"rel27":Relationship(source=Node(id='Social Support', type='Condition'), target=Node(id='Mental Health', type='Condition'), type='IMPROVES'),
"rel28":Relationship(source=Node(id='Sleep Quality', type='Condition'), target=Node(id='Physical Health', type='Condition'), type='AFFECTS'),
"rel29":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Immune System', type='Biological system'), type='WEAKENS'),
"rel30":Relationship(source=Node(id='Cognitive Function', type='Condition'), target=Node(id='Stress', type='Condition'), type='DECREASES'),
"rel31":Relationship(source=Node(id='Diet', type='Condition'), target=Node(id='Stress', type='Condition'), type='INFLUENCES'),
"rel32":Relationship(source=Node(id='Cortisol', type='Hormone'), target=Node(id='Inflammation', type='Condition'), type='INCREASES'),
"rel33":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Genetics', type='Biological factor'), type='INFLUENCED_BY'),
"rel34":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Sleep Quality', type='Health aspect'), type='REDUCES'),
"rel35":Relationship(source=Node(id='Physical Activity', type='Behavior'), target=Node(id='Stress', type='Concept'), type='REDUCES'),
"rel36":Relationship(source=Node(id='Diet', type='Activity'), target=Node(id='Obesity', type='Condition'), type='AFFECTS'),
"rel37":Relationship(source=Node(id='Exercise', type='Activity'), target=Node(id='Stress', type='Condition'), type='DECREASES'),
"rel38":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Physical Health', type='Condition'), type='AFFECTS'),
"rel39":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Cortisol', type='Hormone'), type='INCREASES'),
"rel40":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Mental Health', type='Health aspect'), type='WORSENS'),
"rel41":Relationship(source=Node(id='Depression', type='Condition'), target=Node(id='Sleep Quality', type='Condition'), type='DECREASES'),
"rel42":Relationship(source=Node(id='Physical Activity', type='Activity'), target=Node(id='Blood Pressure', type='Condition'), type='REDUCES'),
"rel43":Relationship(source=Node(id='Sleep Quality', type='Health aspect'), target=Node(id='Immune System', type='Biological system'), type='AFFECTS'),
"rel44":Relationship(source=Node(id='Inflammation', type='Condition'), target=Node(id='Heart Disease', type='Disease'), type='INCREASES_RISK'),
"rel45":Relationship(source=Node(id='Job Satisfaction', type='Emotional state'), target=Node(id='Mental Health', type='Health aspect'), type='IMPROVES'),
"rel46":Relationship(source=Node(id='Social Support', type='Social factor'), target=Node(id='Stress', type='Condition'), type='DECREASES'),
"rel47":Relationship(source=Node(id='Mental Health', type='Health aspect'), target=Node(id='Sleep Quality', type='Health aspect'), type='AFFECTS'),
"rel48":Relationship(source=Node(id='Diet', type='Activity'), target=Node(id='Inflammation', type='Condition'), type='INFLUENCES'),
"rel49":Relationship(source=Node(id='Smoking', type='Activity'), target=Node(id='Physical Health', type='Condition'), type='AFFECTS'),
"rel50":Relationship(source=Node(id='Physical Activity', type='Activity'), target=Node(id='Anxiety', type='Condition'), type='REDUCES'),
"rel51":Relationship(source=Node(id='Productivity', type='Outcome'), target=Node(id='Employee Turnover', type='Outcome'), type='INCREASES'),
"rel52":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Mental Health', type='Health aspect'), type='WORSENS'),
"rel53":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Cognitive Function', type='Function'), type='IMPAIRS'),
"rel54":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Social Support', type='Activity'), type='REDUCES'),
"rel55":Relationship(source=Node(id='Social Support', type='Activity'), target=Node(id='Heart Disease', type='Disease'), type='INFLUENCES_RISK'),
"rel56":Relationship(source=Node(id='Exercise', type='Lifestyle factor'), target=Node(id='Physical Health', type='Condition'), type='IMPROVES'),
"rel57":Relationship(source=Node(id='Social Support', type='Activity'), target=Node(id='Anxiety', type='Condition'), type='REDUCES'),
"rel58":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Mental Health', type='Condition'), type='DETERIORATES'),
"rel59":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Immune System', type='System'), type='WEAKENS'),
"rel60":Relationship(source=Node(id='Cortisol', type='Hormone'), target=Node(id='Immune System', type='Biological system'), type='SUPPRESSES'),
"rel61":Relationship(source=Node(id='Diet', type='Factor'), target=Node(id='Inflammation', type='Condition'), type='INFLUENCES'),
"rel62":Relationship(source=Node(id='Genetics', type='Factor'), target=Node(id='Stress', type='Condition'), type='INFLUENCES'),
"rel63":Relationship(source=Node(id='Mental Health', type='Condition'), target=Node(id='Cognitive Function', type='Condition'), type='INFLUENCES'),
"rel64":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Diet', type='Activity'), type='NEGATIVELY_AFFECTS'),
"rel65":Relationship(source=Node(id='Cognitive Function', type='Condition'), target=Node(id='Mental Health', type='Condition'), type='AFFECTS'),
"rel66":Relationship(source=Node(id='Exercise', type='Activity'), target=Node(id='Stress', type='Condition'), type='REDUCES'),
"rel67":Relationship(source=Node(id='Obesity', type='Condition'), target=Node(id='Blood Pressure', type='Condition'), type='INCREASES'),
"rel68":Relationship(source=Node(id='Inflammation', type='Condition'), target=Node(id='Heart Disease', type='Disease'), type='CONTRIBUTES'),
"rel69":Relationship(source=Node(id='Obesity', type='Condition'), target=Node(id='Heart Disease', type='Disease'), type='INCREASES_RISK'),
"rel70":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Burnout', type='Condition'), type='INCREASES'),
"rel71":Relationship(source=Node(id='Diabetes', type='Disease'), target=Node(id='Stress', type='Condition'), type='INCREASES'),
"rel72":Relationship(source=Node(id='Social Support', type='Aspect'), target=Node(id='Stress', type='Condition'), type='REDUCES'),
"rel73":Relationship(source=Node(id='Mental Health', type='Condition'), target=Node(id='Anxiety', type='Condition'), type='INCLUDES'),
"rel74":Relationship(source=Node(id='Social Support', type='Activity'), target=Node(id='Cognitive Function', type='Condition'), type='IMPROVES'),
"rel75":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Social Support', type='Activity'), type='REQUIRES'),
"rel76":Relationship(source=Node(id='Social Support', type='Social factor'), target=Node(id='Stress', type='Condition'), type='REDUCES'),
"rel77":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Diet', type='Activity'), type='AFFECTS'),
"rel78":Relationship(source=Node(id='Burnout', type='Condition'), target=Node(id='Productivity', type='Outcome'), type='DECREASES'),
"rel79":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Physical Health', type='Health aspect'), type='IMPAIRS'),
"rel80":Relationship(source=Node(id='Mental Health', type='Health aspect'), target=Node(id='Depression', type='Mental condition'), type='INCLUDES'),
"rel81":Relationship(source=Node(id='Mental Health', type='Condition'), target=Node(id='Anxiety', type='Condition'), type='RELATED_TO'),
"rel82":Relationship(source=Node(id='Depression', type='Condition'), target=Node(id='Stress', type='Condition'), type='INCREASES'),
"rel83":Relationship(source=Node(id='Work Environment', type='Environment'), target=Node(id='Job Satisfaction', type='Emotional state'), type='AFFECTS'),
"rel84":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Work Performance', type='Condition'), type='DECREASES'),
"rel85":Relationship(source=Node(id='Diet', type='Activity'), target=Node(id='Inflammation', type='Condition'), type='REDUCES'),
"rel86":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Mental Health', type='Condition'), type='DECREASES'),
"rel87":Relationship(source=Node(id='Diet', type='Behavior'), target=Node(id='Stress', type='Concept'), type='INFLUENCES'),
"rel88":Relationship(source=Node(id='Exercise', type='Activity'), target=Node(id='Stress', type='Concept'), type='REDUCES'),
"rel89":Relationship(source=Node(id='Cognitive Function', type='Condition'), target=Node(id='Mental Health', type='Condition'), type='ASSOCIATED_WITH'),
"rel90":Relationship(source=Node(id='Cognitive Function', type='Condition'), target=Node(id='Stress', type='Condition'), type='AFFECTS'),
"rel91":Relationship(source=Node(id='Job Satisfaction', type='Workplace factor'), target=Node(id='Stress', type='Concept'), type='INFLUENCES'),
"rel92":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Heart Disease', type='Disease'), type='INCREASES'),
"rel93":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Cognitive Function', type='Condition'), type='IMPAIRS'),
"rel94":Relationship(source=Node(id='Diet', type='Activity'), target=Node(id='Mental Health', type='Condition'), type='INFLUENCES'),
"rel95":Relationship(source=Node(id='Social Support', type='Activity'), target=Node(id='Depression', type='Condition'), type='REDUCES'),
"rel96":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Sleep Quality', type='Condition'), type='DECREASES'),
"rel97":Relationship(source=Node(id='Job Satisfaction', type='Psychological factor'), target=Node(id='Stress', type='Concept'), type='REDUCES'),
"rel98":Relationship(source=Node(id='Diet', type='Lifestyle'), target=Node(id='Stress', type='Condition'), type='INFLUENCES'),
"rel99":Relationship(source=Node(id='Alcohol Consumption', type='Lifestyle'), target=Node(id='Stress', type='Condition'), type='INCREASES'),
"rel100":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Inflammation', type='Biological process'), type='INCREASES'),
"rel101":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Mental Health', type='Condition'), type='DEGRADES'),
"rel102":Relationship(source=Node(id='Mental Health', type='Condition'), target=Node(id='Anxiety', type='Condition'), type='AFFECTS'),
"rel103":Relationship(source=Node(id='Job Satisfaction', type='Condition'), target=Node(id='Burnout', type='Condition'), type='DECREASES'),
"rel104":Relationship(source=Node(id='Work Environment', type='Condition'), target=Node(id='Stress', type='Condition'), type='INFLUENCES'),
"rel105":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Work Environment', type='Environment'), type='INFLUENCED_BY'),
"rel106":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Mental Health', type='Health aspect'), type='DETERIORATES'),
"rel107":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Social Support', type='Social factor'), type='REDUCES'),
"rel108":Relationship(source=Node(id='Blood Pressure', type='Condition'), target=Node(id='Stress', type='Condition'), type='INCREASES'),
"rel109":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Social Support', type='Condition'), type='DECREASES'),
"rel110":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Mental Health', type='Condition'), type='IMPAIRS'),
"rel111":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Anxiety', type='Emotional state'), type='INCREASES'),
"rel112":Relationship(source=Node(id='Sleep Quality', type='Condition'), target=Node(id='Cognitive Function', type='Condition'), type='AFFECTS'),
"rel113":Relationship(source=Node(id='Sleep Quality', type='Condition'), target=Node(id='Mental Health', type='Condition'), type='IMPROVES'),
"rel114":Relationship(source=Node(id='Diet', type='Activity'), target=Node(id='Stress', type='Condition'), type='INFLUENCES'),
"rel115":Relationship(source=Node(id='Cortisol', type='Hormone'), target=Node(id='Inflammation', type='Biological process'), type='PROMOTES'),
"rel116":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Diet', type='Lifestyle factor'), type='WORSENS'),
"rel117":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Mental Health', type='Health aspect'), type='DETERIORATES'),
"rel118":Relationship(source=Node(id='Diet', type='Lifestyle factor'), target=Node(id='Stress', type='Condition'), type='INFLUENCES'),
"rel119":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Diet', type='Activity'), type='WORSENS'),
"rel120":Relationship(source=Node(id='Physical Activity', type='Activity'), target=Node(id='Obesity', type='Condition'), type='REDUCES'),
"rel121":Relationship(source=Node(id='Job Satisfaction', type='Emotional state'), target=Node(id='Mental Health', type='Health aspect'), type='AFFECTS'),
"rel122":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Productivity', type='Outcome'), type='DECREASES'),
"rel123":Relationship(source=Node(id='Social Support', type='Factor'), target=Node(id='Stress', type='Condition'), type='DECREASES'),
"rel124":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Work Environment', type='Factor'), type='WORSENS'),
"rel125":Relationship(source=Node(id='Mental Health', type='Condition'), target=Node(id='Depression', type='Condition'), type='INCLUDES'),
"rel126":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Sleep Quality', type='Condition'), type='REDUCES'),
"rel127":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Work Environment', type='Environment'), type='WORSENS'),
"rel128":Relationship(source=Node(id='Social Support', type='Factor'), target=Node(id='Mental Health', type='Condition'), type='IMPROVES'),
"rel129":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Diabetes', type='Disease'), type='INCREASES_RISK_OF'),
"rel130":Relationship(source=Node(id='Cognitive Function', type='Condition'), target=Node(id='Aging', type='Condition'), type='DECLINES_WITH'),
"rel131":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Inflammation', type='Biological process'), type='INCREASES'),
"rel132":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Anxiety', type='Mental condition'), type='INCREASES'),
"rel133":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Job Satisfaction', type='Emotional state'), type='DECREASES'),
"rel134":Relationship(source=Node(id='Diet', type='Factor'), target=Node(id='Physical Health', type='Condition'), type='IMPROVES'),
"rel135":Relationship(source=Node(id='Cortisol', type='Hormone'), target=Node(id='Diabetes', type='Disease'), type='INCREASES_RISK'),
"rel136":Relationship(source=Node(id='Mental Health', type='Condition'), target=Node(id='Social Support', type='Activity'), type='INFLUENCES'),
"rel137":Relationship(source=Node(id='Physical Activity', type='Activity'), target=Node(id='Mental Health', type='Condition'), type='IMPROVES'),
"rel138":Relationship(source=Node(id='Immune System', type='Biological system'), target=Node(id='Inflammation', type='Biological process'), type='REGULATES'),
"rel139":Relationship(source=Node(id='Physical Activity', type='Activity'), target=Node(id='Cortisol', type='Hormone'), type='REDUCES'),
"rel140":Relationship(source=Node(id='Mental Health', type='Condition'), target=Node(id='Depression', type='Condition'), type='RELATED_TO'),
"rel141":Relationship(source=Node(id='Job Satisfaction', type='Condition'), target=Node(id='Burnout', type='Condition'), type='REDUCES'),
"rel142":Relationship(source=Node(id='Exercise', type='Factor'), target=Node(id='Physical Health', type='Condition'), type='IMPROVES'),
"rel143":Relationship(source=Node(id='Social Support', type='Condition'), target=Node(id='Stress', type='Condition'), type='DECREASES'),
"rel144":Relationship(source=Node(id='Work Environment', type='Factor'), target=Node(id='Stress', type='Condition'), type='INFLUENCES'),
"rel145":Relationship(source=Node(id='Genetics', type='Aspect'), target=Node(id='Stress', type='Condition'), type='INFLUENCES'),
"rel146":Relationship(source=Node(id='Mental Health', type='Health aspect'), target=Node(id='Anxiety', type='Mental condition'), type='INCLUDES'),
"rel147":Relationship(source=Node(id='Sleep Quality', type='Health aspect'), target=Node(id='Mental Health', type='Health aspect'), type='AFFECTS'),
"rel148":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Heart Disease', type='Disease'), type='INCREASES_RISK_OF'),
"rel149":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Social Support', type='Condition'), type='REDUCES'),
"rel150":Relationship(source=Node(id='Social Support', type='Behavior'), target=Node(id='Stress', type='Condition'), type='REDUCES'),
"rel151":Relationship(source=Node(id='Cortisol', type='Hormone'), target=Node(id='Blood Pressure', type='Condition'), type='INCREASES'),
"rel152":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Mental Health', type='Condition'), type='AFFECTS'),
"rel153":Relationship(source=Node(id='Sleep Quality', type='Condition'), target=Node(id='Mental Health', type='Condition'), type='INFLUENCES'),
"rel154":Relationship(source=Node(id='Work Environment', type='Environment'), target=Node(id='Stress', type='Condition'), type='INDUCES'),
"rel155":Relationship(source=Node(id='Immune System', type='Biological system'), target=Node(id='Inflammation', type='Condition'), type='REDUCES'),
"rel156":Relationship(source=Node(id='Heart Rate', type='Physiological measure'), target=Node(id='Stress', type='Condition'), type='INCREASES'),
"rel157":Relationship(source=Node(id='Smoking', type='Activity'), target=Node(id='Stress', type='Condition'), type='INCREASES'),
"rel158":Relationship(source=Node(id='Cortisol', type='Hormone'), target=Node(id='Sleep Quality', type='Condition'), type='DECREASES'),
"rel159":Relationship(source=Node(id='Cortisol', type='Hormone'), target=Node(id='Inflammation', type='Condition'), type='REGULATES'),
"rel160":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Genetics', type='Biological factor'), type='INFLUENCED_BY'),
"rel161":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Physical Health', type='Condition'), type='DETERIORATES'),
"rel162":Relationship(source=Node(id='Work Environment', type='Environment'), target=Node(id='Stress', type='Condition'), type='INFLUENCES'),
"rel163":Relationship(source=Node(id='Social Support', type='Factor'), target=Node(id='Stress', type='Condition'), type='REDUCES'),
"rel164":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Physical Activity', type='Activity'), type='DECREASES'),
"rel165":Relationship(source=Node(id='Work Environment', type='Environment'), target=Node(id='Job Satisfaction', type='Condition'), type='INFLUENCES'),
"rel166":Relationship(source=Node(id='Physical Activity', type='Activity'), target=Node(id='Depression', type='Condition'), type='REDUCES'),
"rel167":Relationship(source=Node(id='Burnout', type='Condition'), target=Node(id='Mental Health', type='Condition'), type='AFFECTS'),
"rel168":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Depression', type='Mental condition'), type='INCREASES'),
"rel169":Relationship(source=Node(id='Physical Activity', type='Activity'), target=Node(id='Stress', type='Condition'), type='REDUCES'),
"rel170":Relationship(source=Node(id='Mental Health', type='Condition'), target=Node(id='Physical Activity', type='Activity'), type='IMPROVES'),
"rel171":Relationship(source=Node(id='Exercise', type='Lifestyle factor'), target=Node(id='Stress', type='Condition'), type='REDUCES'),
"rel172":Relationship(source=Node(id='Diet', type='Activity'), target=Node(id='Heart Disease', type='Disease'), type='INFLUENCES_RISK'),
"rel173":Relationship(source=Node(id='Genetics', type='Biological factor'), target=Node(id='Stress', type='Condition'), type='INFLUENCES'),
"rel174":Relationship(source=Node(id='Blood Pressure', type='Physiological measure'), target=Node(id='Stress', type='Condition'), type='INCREASES'),
"rel175":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Immune System', type='Biological system'), type='WEAKENS'),
"rel176":Relationship(source=Node(id='Work Environment', type='Environment'), target=Node(id='Stress', type='Condition'), type='INCREASES'),
"rel177":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Depression', type='Emotional state'), type='INCREASES'),
"rel178":Relationship(source=Node(id='Social Support', type='Condition'), target=Node(id='Stress', type='Condition'), type='REDUCES'),
"rel179":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Work Environment', type='Environment'), type='AFFECTED_BY'),
"rel180":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Diet', type='Condition'), type='AFFECTS'),
"rel181":Relationship(source=Node(id='Sleep Quality', type='Health aspect'), target=Node(id='Immune System', type='Biological system'), type='IMPROVES'),
"rel182":Relationship(source=Node(id='Diet', type='Factor'), target=Node(id='Physical Health', type='Condition'), type='INFLUENCES'),
"rel183":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Heart Disease', type='Disease'), type='INCREASES_RISK_OF'),
"rel184":Relationship(source=Node(id='Social Support', type='Social factor'), target=Node(id='Stress', type='Concept'), type='REDUCES'),
"rel185":Relationship(source=Node(id='Mental Health', type='Condition'), target=Node(id='Physical Activity', type='Activity'), type='INFLUENCES'),
"rel186":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Cortisol', type='Hormone'), type='INCREASES'),
"rel187":Relationship(source=Node(id='Social Support', type='Social factor'), target=Node(id='Mental Health', type='Health aspect'), type='IMPROVES'),
"rel188":Relationship(source=Node(id='Diet', type='Activity'), target=Node(id='Diabetes', type='Disease'), type='INFLUENCES'),
"rel189":Relationship(source=Node(id='Diet', type='Lifestyle factor'), target=Node(id='Physical Health', type='Condition'), type='IMPROVES'),
"rel190":Relationship(source=Node(id='Heart Disease', type='Disease'), target=Node(id='Blood Pressure', type='Condition'), type='INCREASES'),
"rel191":Relationship(source=Node(id='Diet', type='Activity'), target=Node(id='Depression', type='Condition'), type='INFLUENCES'),
"rel192":Relationship(source=Node(id='Work Environment', type='Environment'), target=Node(id='Stress', type='Condition'), type='CAUSES'),
"rel193":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Obesity', type='Condition'), type='INCREASES_RISK_OF'),
"rel194":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Physical Activity', type='Activity'), type='REDUCES'),
"rel195":Relationship(source=Node(id='Cortisol', type='Hormone'), target=Node(id='Inflammation', type='Biological process'), type='INCREASES'),
"rel196":Relationship(source=Node(id='Work Environment', type='Environment'), target=Node(id='Social Support', type='Social factor'), type='INFLUENCES'),
"rel197":Relationship(source=Node(id='Job Satisfaction', type='Condition'), target=Node(id='Productivity', type='Condition'), type='INCREASES'),
"rel198":Relationship(source=Node(id='Diet', type='Aspect'), target=Node(id='Stress', type='Condition'), type='INFLUENCES'),
"rel199":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Mental Health', type='Condition'), type='WORSENS'),
"rel200":Relationship(source=Node(id='Diet', type='Activity'), target=Node(id='Stress', type='Condition'), type='DECREASES'),
"rel201":Relationship(source=Node(id='Sleep Quality', type='Condition'), target=Node(id='Mental Health', type='Condition'), type='AFFECTS'),
"rel202":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Obesity', type='Condition'), type='INCREASES_RISK'),
"rel203":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Heart Disease', type='Condition'), type='INCREASES_RISK'),
"rel204":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Physical Activity', type='Behavior'), type='DECREASES'),
"rel205":Relationship(source=Node(id='Physical Activity', type='Activity'), target=Node(id='Stress', type='Concept'), type='REDUCES'),
"rel206":Relationship(source=Node(id='Mental Health', type='Condition'), target=Node(id='Diet', type='Activity'), type='INFLUENCES'),
"rel207":Relationship(source=Node(id='Diet', type='Activity'), target=Node(id='Heart Disease', type='Disease'), type='INFLUENCES'),
"rel208":Relationship(source=Node(id='Diet', type='Factor'), target=Node(id='Stress', type='Condition'), type='INFLUENCES'),
"rel209":Relationship(source=Node(id='Genetics', type='Factor'), target=Node(id='Heart Disease', type='Disease'), type='INFLUENCES'),
"rel210":Relationship(source=Node(id='Physical Activity', type='Activity'), target=Node(id='Stress', type='Condition'), type='DECREASES'),
"rel211":Relationship(source=Node(id='Job Satisfaction', type='Condition'), target=Node(id='Stress', type='Condition'), type='INFLUENCES'),
"rel212":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Social Support', type='Factor'), type='DECREASES'),
"rel213":Relationship(source=Node(id='Mental Health', type='Health aspect'), target=Node(id='Depression', type='Condition'), type='INCLUDES'),
"rel214":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Social Support', type='Social factor'), type='DECREASES'),
"rel215":Relationship(source=Node(id='Social Support', type='Social factor'), target=Node(id='Mental Health', type='Condition'), type='IMPROVES'),
"rel216":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Social Relationships', type='Condition'), type='DETERIORATES'),
"rel217":Relationship(source=Node(id='Burnout', type='Condition'), target=Node(id='Mental Health', type='Health aspect'), type='AFFECTS'),
"rel218":Relationship(source=Node(id='Diet', type='Activity'), target=Node(id='Sleep Quality', type='Condition'), type='INFLUENCES'),
"rel219":Relationship(source=Node(id='Physical Activity', type='Behavior'), target=Node(id='Stress', type='Condition'), type='REDUCES'),
"rel220":Relationship(source=Node(id='Diet', type='Lifestyle factor'), target=Node(id='Inflammation', type='Biological process'), type='REDUCES'),
"rel221":Relationship(source=Node(id='Inflammation', type='Biological process'), target=Node(id='Heart Disease', type='Disease'), type='CONTRIBUTES_TO'),
"rel222":Relationship(source=Node(id='Work Environment', type='Environment'), target=Node(id='Job Satisfaction', type='Emotional state'), type='INFLUENCES'),
"rel223":Relationship(source=Node(id='Physical Activity', type='Activity'), target=Node(id='Diabetes', type='Disease'), type='REDUCES_RISK'),
"rel224":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Sleep Quality', type='Health aspect'), type='DECREASES'),
"rel225":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Inflammation', type='Condition'), type='INCREASES'),
"rel226":Relationship(source=Node(id='Diet', type='Lifestyle factor'), target=Node(id='Stress', type='Concept'), type='INFLUENCES'),
"rel227":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Diet', type='Factor'), type='INFLUENCED_BY'),
"rel228":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Memory', type='Condition'), type='IMPAIRS'),
"rel229":Relationship(source=Node(id='Blood Pressure', type='Condition'), target=Node(id='Heart Disease', type='Disease'), type='INCREASES_RISK'),
"rel230":Relationship(source=Node(id='Diet', type='Lifestyle factor'), target=Node(id='Inflammation', type='Condition'), type='INFLUENCES'),
"rel231":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Blood Pressure', type='Condition'), type='INCREASES'),
"rel232":Relationship(source=Node(id='Social Support', type='Activity'), target=Node(id='Stress', type='Condition'), type='REDUCES'),
"rel233":Relationship(source=Node(id='Work Environment', type='Environment'), target=Node(id='Job Satisfaction', type='Condition'), type='AFFECTS'),
"rel234":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Heart Disease', type='Disease'), type='INCREASES_RISK'),
"rel235":Relationship(source=Node(id='Cortisol', type='Hormone'), target=Node(id='Immune System', type='Biological system'), type='WEAKENS'),
"rel236":Relationship(source=Node(id='Mental Health', type='Condition'), target=Node(id='Depression', type='Condition'), type='AFFECTS'),
"rel237":Relationship(source=Node(id='Cortisol', type='Hormone'), target=Node(id='Immune System', type='System'), type='SUPPRESSES'),
"rel238":Relationship(source=Node(id='Diet', type='Behavior'), target=Node(id='Inflammation', type='Condition'), type='REDUCES'),
"rel239":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Exercise', type='Activity'), type='REDUCED_BY'),
"rel240":Relationship(source=Node(id='Cortisol', type='Hormone'), target=Node(id='Anxiety', type='Condition'), type='INCREASES'),
"rel241":Relationship(source=Node(id='Physical Activity', type='Activity'), target=Node(id='Sleep Quality', type='Condition'), type='IMPROVES'),
"rel242":Relationship(source=Node(id='Physical Activity', type='Activity'), target=Node(id='Cognitive Function', type='Condition'), type='IMPROVES'),
"rel243":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Diet', type='Factor'), type='WORSENS'),
"rel244":Relationship(source=Node(id='Sleep Quality', type='Health aspect'), target=Node(id='Heart Disease', type='Disease'), type='AFFECTS'),
"rel245":Relationship(source=Node(id='Smoking', type='Lifestyle'), target=Node(id='Stress', type='Condition'), type='INCREASES'),
"rel246":Relationship(source=Node(id='Cortisol', type='Hormone'), target=Node(id='Inflammation', type='Condition'), type='PROMOTES'),
"rel247":Relationship(source=Node(id='Cortisol', type='Hormone'), target=Node(id='Obesity', type='Condition'), type='CONTRIBUTES_TO'),
"rel248":Relationship(source=Node(id='Obesity', type='Condition'), target=Node(id='Stress', type='Condition'), type='INCREASES'),
"rel249":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Social Support', type='Factor'), type='REDUCES'),
"rel250":Relationship(source=Node(id='Sleep Quality', type='Condition'), target=Node(id='Cognitive Function', type='Condition'), type='IMPROVES'),
"rel251":Relationship(source=Node(id='Work Environment', type='Environment'), target=Node(id='Stress', type='Condition'), type='CONTRIBUTES_TO'),
"rel252":Relationship(source=Node(id='Inflammation', type='Condition'), target=Node(id='Diabetes', type='Disease'), type='CONTRIBUTES_TO'),
"rel253":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Social Support', type='Social factor'), type='REDUCES'),
"rel254":Relationship(source=Node(id='Job Satisfaction', type='Psychological factor'), target=Node(id='Stress', type='Condition'), type='INFLUENCES'),
"rel255":Relationship(source=Node(id='Job Satisfaction', type='Condition'), target=Node(id='Stress', type='Condition'), type='REDUCES'),
"rel256":Relationship(source=Node(id='Diet', type='Activity'), target=Node(id='Obesity', type='Condition'), type='INFLUENCES'),
"rel257":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Depression', type='Condition'), type='INCREASES'),
"rel258":Relationship(source=Node(id='Obesity', type='Condition'), target=Node(id='Diabetes', type='Disease'), type='INCREASES_RISK_OF'),
"rel259":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Anxiety', type='Condition'), type='INCREASES'),
"rel260":Relationship(source=Node(id='Diet', type='Activity'), target=Node(id='Anxiety', type='Condition'), type='INFLUENCES'),
"rel261":Relationship(source=Node(id='Immune System', type='Biological system'), target=Node(id='Inflammation', type='Condition'), type='REGULATES'),
"rel262":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Sleep Quality', type='Health aspect'), type='REDUCES'),
"rel263":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Mental Health', type='Health aspect'), type='IMPAIRS'),
"rel264":Relationship(source=Node(id='Diet', type='Activity'), target=Node(id='Diabetes', type='Disease'), type='AFFECTS'),
"rel265":Relationship(source=Node(id='Work Environment', type='Environment'), target=Node(id='Stress', type='Concept'), type='INFLUENCES'),
"rel266":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Job Satisfaction', type='Psychological factor'), type='DECREASES'),
"rel267":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Mental Health', type='Aspect'), type='AFFECTS'),
"rel268":Relationship(source=Node(id='Social Support', type='Activity'), target=Node(id='Mental Health', type='Condition'), type='IMPROVES'),
"rel269":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Work Environment', type='Environment'), type='AFFECTS'),
"rel270":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Learning', type='Condition'), type='IMPAIRS'),
"rel271":Relationship(source=Node(id='Alcohol Consumption', type='Activity'), target=Node(id='Stress', type='Condition'), type='INCREASES'),
"rel272":Relationship(source=Node(id='Mental Health', type='Health aspect'), target=Node(id='Sleep Quality', type='Health aspect'), type='INFLUENCES'),
"rel273":Relationship(source=Node(id='Stress', type='Concept'), target=Node(id='Heart Disease', type='Disease'), type='INCREASES_RISK'),
"rel274":Relationship(source=Node(id='Obesity', type='Condition'), target=Node(id='Diabetes', type='Disease'), type='INCREASES_RISK'),
"rel275":Relationship(source=Node(id='Sleep Quality', type='Health aspect'), target=Node(id='Immune System', type='Biological system'), type='STRENGTHENS'),
"rel276":Relationship(source=Node(id='Inflammation', type='Condition'), target=Node(id='Heart Disease', type='Disease'), type='CONTRIBUTES_TO'),
"rel277":Relationship(source=Node(id='Work Environment', type='Environment'), target=Node(id='Social Support', type='Social factor'), type='AFFECTS'),
"rel278":Relationship(source=Node(id='Diet', type='Lifestyle factor'), target=Node(id='Inflammation', type='Condition'), type='REDUCES'),
"rel279":Relationship(source=Node(id='Genetics', type='Biological factor'), target=Node(id='Stress', type='Concept'), type='INFLUENCES'),
"rel280":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Job Satisfaction', type='Condition'), type='DECREASES'),
"rel281":Relationship(source=Node(id='Diet', type='Behavior'), target=Node(id='Stress', type='Condition'), type='INFLUENCES'),
"rel282":Relationship(source=Node(id='Job Satisfaction', type='Psychological factor'), target=Node(id='Stress', type='Concept'), type='INFLUENCES'),
"rel283":Relationship(source=Node(id='Sleep Quality', type='Health aspect'), target=Node(id='Mental Health', type='Health aspect'), type='IMPROVES'),
"rel284":Relationship(source=Node(id='Physical Activity', type='Activity'), target=Node(id='Heart Disease', type='Disease'), type='REDUCES_RISK'),
"rel285":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Mental Health', type='Health aspect'), type='AFFECTS'),
"rel286":Relationship(source=Node(id='Anxiety', type='Condition'), target=Node(id='Sleep Quality', type='Condition'), type='DECREASES'),
"rel287":Relationship(source=Node(id='Stress', type='Condition'), target=Node(id='Sleep Quality', type='Aspect'), type='DECREASES'),
"rel288":Relationship(source=Node(id='Diet', type='Activity'), target=Node(id='Cognitive Function', type='Condition'), type='INFLUENCES')
}